### ISSUE TITLE
Multiple errors when running Anki from flathub

### ISSUE THREAD

**Issue by mainrs** [flathub/net.ankiweb.Anki#118] opened 2023-11-02 15:08 UTC
The raw output contains following warnings and errors:

- `libinput-config.so` cannot be loaded
- Running with QT5 compatibility shim
- Path `/usr` is reserved by Flatpak

Here is the raw output:

```console
❯ flatpak run net.ankiweb.Anki --version
F: Not sharing "/usr/share/themes/Catppuccin-Latte-Standard-Mauve-Light" with sandbox: Path "/usr" is reserved by Flatpak
ERROR: ld.so: object '/usr/lib/libinput-config.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Anki starting...
Initial setup...
Running with temporary Qt5 compatibility shims.
Run with DISABLE_QT5_COMPAT=1 to confirm compatibility with Qt6.
Preparing to run...
Anki 2.1.66
``` 

The first point seems to be pretty easily fixable. Just adding the dependency to the flathub package. 
The second one I do not really understand. What does it mean?
The third point I also do not understand. It has nothing to do with this package, but since I am already on an issue tracker with people that know how flatpak works, I thought I might ask as well. 

P.S.: Is there a generic way to inject more dependencies into a flathub package? For example, if an addon needs a specific CLI tool installed.

**Comment by rayes0** [comment] 2023-11-04 00:21
These warnings seem fine and should not impede app function.

- libinput LD_PRELOAD: I cannot reproduce this and am unsure why libinput is in your LD_PRELOAD. Have you set a custom LD_PRELOAD for flatpaks?
- Qt5 compatibility shims: These are expected and are on by default. Anki switched to PyQt6 a while back, so the shims fix some issues with addons that still use PyQt5.
- Path `/usr` is reserved by flatpak: You are attempting to allow access to the host `/usr` (I'm guessing you have set a permission like `filesystem=/usr/share/themes:ro`). `/usr` is already used in the sandbox. You will need to use something like `filesystem=host-os:ro` and access `/usr` via `/var/run/host/usr` path. For more info: https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access

As for running a CLI tool from an addon, the easiest way I can think of is adding the `host-os` permission, and adding `/var/run/host/bin` to `PATH`in the sandbox. This will obviously weaken the sandbox. If you are able to modify the addon, take a look at https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-spawn.

**Comment by mainrs** [comment] 2023-11-04 13:05
Concerning point number 3, I am doing this for a theme, that is correct. As of now, the theming of flatpak apps does not match the theming of my whole system. I tried giving it access to `/usr/share/themes/`, since that's where my GTK themes are stored.

**Comment by rayes0** [comment] 2023-11-07 07:21
Does the LD_PRELOAD happen with all flatpaks, or only this one?

As for the themes, /usr is a blacklisted path since its already used in the sandbox and so can't be forwarded at the same location in the sandbox. You will need to either set `host-os` and point your apps to use the theme in /var/run/host/usr, or install the themes into your home directory `~/.themes` or somwhere similar that your apps recognize, and set the `filesystem=home:ro` permission (/home is not blacklisted and will get forwarded directly to /home in the sandbox).

**Comment by rayes0** [comment] 2023-11-07 07:23
Since these issues seem specific to your system and not issues with this flatpak in general, closing this issue for now, but feel free to keep commenting if you need more help.

**Closed by rayes0** 2023-11-07 07:23 UTC
